# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-30 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_hellp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hellp',
        ),
    ]
